language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - 2.0.0
gemfile:
  - test/gemfiles/Gemfile.rails-2.3.x
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails.4.0.x
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-2.3.x
    - rvm: 1.8.7
      gemfile: test/gemfiles/Gemfile.rails.4.0.x
    - rvm: ree
      gemfile: test/gemfiles/Gemfile.rails.4.0.x